name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
      - main

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAILFIT_TODO }}"
          projectId: mailfit-todo
